kind: pipeline
type: docker
name: default

steps:
  - name: dependencies-check
    image: clojure:lein-2.8.3
    commands:
      - lein ancient

  - name: lint-format
    image: clojure:lein-2.8.3
    commands:
      - lein kibit

  - name: lint-style
    image: clojure:lein-2.8.3
    commands:
      - lein cljfmt check

  - name: build
    image: clojure:lein-2.8.3
    commands:
      - lein fig:min

  - name: deploy
    image: node:10.16.3-alpine
    commands:
      - npm install -g firebase-tools
      - firebase deploy --only hosting:dangan-clj
    environment:
      FIREBASE_TOKEN:
        from_secret: firebase_token
    when:
      branch:
        - master
